image: gitpod/workspace-full

tasks:
  - name: Setup Android SDK
    init: |
      # Install Android SDK
      wget -q https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
      unzip -q commandlinetools-linux-8512546_latest.zip
      mkdir -p android-sdk/cmdline-tools
      mv cmdline-tools android-sdk/cmdline-tools/latest
      
      # Set environment variables
      export ANDROID_HOME=$PWD/android-sdk
      export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools
      
      # Accept licenses and install required packages
      yes | sdkmanager --licenses
      sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0"
      
      # Install dependencies
      npm install
      
    command: |
      export ANDROID_HOME=$PWD/android-sdk
      export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools
      echo "🚀 Android development environment ready!"
      echo "Run 'npm run build && npx cap sync android && cd android && ./gradlew assembleDebug' to build APK"

ports:
  - port: 3000
    onOpen: open-browser
    description: Vite dev server
  - port: 5000
    onOpen: ignore
    description: Express server

vscode:
  extensions:
    - bradlc.vscode-tailwindcss
    - ms-vscode.vscode-typescript-next
    - esbenp.prettier-vscode
