name: CI/CD Pipeline

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Type check
      run: npm run check
      
    - name: Build web assets
      run: npm run build
      
    - name: Test build output
      run: |
        ls -la dist/
        echo "Build completed successfully"

  android-build:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/development'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
          - name: Setup Android SDK
      run: |
        # Install Android SDK command line tools
        sudo apt-get update
        sudo apt-get install -y wget unzip
        
        # Set up Android SDK environment
        export ANDROID_HOME=${GITHUB_WORKSPACE}/android-sdk
        export ANDROID_SDK_ROOT=${ANDROID_HOME}
        mkdir -p ${ANDROID_HOME}/cmdline-tools
        
        # Download and install command line tools
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
        unzip -q commandlinetools-linux-11076708_latest.zip -d ${ANDROID_HOME}/cmdline-tools
        mv ${ANDROID_HOME}/cmdline-tools/cmdline-tools ${ANDROID_HOME}/cmdline-tools/latest
        
        # Add to PATH
        export PATH=${ANDROID_HOME}/cmdline-tools/latest/bin:${ANDROID_HOME}/platform-tools:${PATH}
        echo "${ANDROID_HOME}/cmdline-tools/latest/bin" >> $GITHUB_PATH
        echo "${ANDROID_HOME}/platform-tools" >> $GITHUB_PATH
        echo "ANDROID_HOME=${ANDROID_HOME}" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=${ANDROID_HOME}" >> $GITHUB_ENV
        
        # Accept licenses and install packages
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "build-tools;35.0.0" "platforms;android-35"
      
    - name: Install dependencies
      run: npm ci
      
    - name: Build web assets
      run: npm run build
      
    - name: Setup Capacitor
      run: |
        npm install -g @capacitor/cli
        npx cap sync android
        
    - name: Grant execute permission for gradlew
      run: chmod +x android/gradlew
      
    - name: Build Debug APK
      run: |
        cd android
        ./gradlew assembleDebug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: ravintola-tirva-${{ github.ref_name }}-${{ github.run_number }}
        path: android/app/build/outputs/apk/debug/*.apk
        retention-days: 7
